package com.cuit.june.mapper;

import com.cuit.june.pojo.TblSupplier;

import java.math.BigDecimal;

public interface TblSupplierMapper extends BaseMapper<TblSupplier>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SUPPLIER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SUPPLIER
     *
     * @mbggenerated
     */
    int insert(TblSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SUPPLIER
     *
     * @mbggenerated
     */
    int insertSelective(TblSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SUPPLIER
     *
     * @mbggenerated
     */
    TblSupplier selectByPrimaryKey(BigDecimal pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SUPPLIER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SUPPLIER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblSupplier record);
}