package com.cuit.june.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TblGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GOODS.PK_ID
     *
     * @mbggenerated
     */
    private BigDecimal pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GOODS.GOODS_NUMBER
     *
     * @mbggenerated
     */
    private String goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GOODS.GOODS_NAME
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GOODS.GOODS_PRICE
     *
     * @mbggenerated
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GOODS.GOODS_PRODUCTIONDATE
     *
     * @mbggenerated
     */
    private Date goodsProductiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GOODS.GOODS_SHELFLIFE
     *
     * @mbggenerated
     */
    private Date goodsShelflife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_GOODS.GOODS_INVENTORY
     *
     * @mbggenerated
     */
    private Double goodsInventory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_GOODS.PK_ID
     *
     * @return the value of TBL_GOODS.PK_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_GOODS.PK_ID
     *
     * @param pkId the value for TBL_GOODS.PK_ID
     *
     * @mbggenerated
     */
    public void setPkId(BigDecimal pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_GOODS.GOODS_NUMBER
     *
     * @return the value of TBL_GOODS.GOODS_NUMBER
     *
     * @mbggenerated
     */
    public String getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_GOODS.GOODS_NUMBER
     *
     * @param goodsNumber the value for TBL_GOODS.GOODS_NUMBER
     *
     * @mbggenerated
     */
    public void setGoodsNumber(String goodsNumber) {
        this.goodsNumber = goodsNumber == null ? null : goodsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_GOODS.GOODS_NAME
     *
     * @return the value of TBL_GOODS.GOODS_NAME
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_GOODS.GOODS_NAME
     *
     * @param goodsName the value for TBL_GOODS.GOODS_NAME
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_GOODS.GOODS_PRICE
     *
     * @return the value of TBL_GOODS.GOODS_PRICE
     *
     * @mbggenerated
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_GOODS.GOODS_PRICE
     *
     * @param goodsPrice the value for TBL_GOODS.GOODS_PRICE
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_GOODS.GOODS_PRODUCTIONDATE
     *
     * @return the value of TBL_GOODS.GOODS_PRODUCTIONDATE
     *
     * @mbggenerated
     */
    public Date getGoodsProductiondate() {
        return goodsProductiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_GOODS.GOODS_PRODUCTIONDATE
     *
     * @param goodsProductiondate the value for TBL_GOODS.GOODS_PRODUCTIONDATE
     *
     * @mbggenerated
     */
    public void setGoodsProductiondate(Date goodsProductiondate) {
        this.goodsProductiondate = goodsProductiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_GOODS.GOODS_SHELFLIFE
     *
     * @return the value of TBL_GOODS.GOODS_SHELFLIFE
     *
     * @mbggenerated
     */
    public Date getGoodsShelflife() {
        return goodsShelflife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_GOODS.GOODS_SHELFLIFE
     *
     * @param goodsShelflife the value for TBL_GOODS.GOODS_SHELFLIFE
     *
     * @mbggenerated
     */
    public void setGoodsShelflife(Date goodsShelflife) {
        this.goodsShelflife = goodsShelflife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_GOODS.GOODS_INVENTORY
     *
     * @return the value of TBL_GOODS.GOODS_INVENTORY
     *
     * @mbggenerated
     */
    public Double getGoodsInventory() {
        return goodsInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_GOODS.GOODS_INVENTORY
     *
     * @param goodsInventory the value for TBL_GOODS.GOODS_INVENTORY
     *
     * @mbggenerated
     */
    public void setGoodsInventory(Double goodsInventory) {
        this.goodsInventory = goodsInventory;
    }
}