package com.cuit.june.pojo;

import java.math.BigDecimal;

public class TblRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECORDS.PK_ID
     *
     * @mbggenerated
     */
    private BigDecimal pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECORDS.FK_GOODS_ID
     *
     * @mbggenerated
     */
    private BigDecimal fkGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECORDS.FK_SUPPL_ID
     *
     * @mbggenerated
     */
    private BigDecimal fkSupplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECORDS.RECO_NUMBER
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECORDS.RECO_DATE
     *
     * @mbggenerated
     */
    private String recoDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECORDS.RECO_OPERATION
     *
     * @mbggenerated
     */
    private String recoOperation;

    /**
     * 操作人员
     */
    private String recoRecoder;

    /**
     * 操作数量
     */
    private String recoNumber;

    public TblRecords(BigDecimal fkGoodsId, String recoDate, String recoOperation, String recoRecoder, String recoNumber) {
        this.fkGoodsId = fkGoodsId;
        this.recoDate = recoDate;
        this.recoOperation = recoOperation;
        this.recoRecoder = recoRecoder;
        this.recoNumber = recoNumber;
    }

    public TblRecords(){}
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECORDS.PK_ID
     *
     * @return the value of TBL_RECORDS.PK_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECORDS.PK_ID
     *
     * @param pkId the value for TBL_RECORDS.PK_ID
     *
     * @mbggenerated
     */
    public void setPkId(BigDecimal pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECORDS.FK_GOODS_ID
     *
     * @return the value of TBL_RECORDS.FK_GOODS_ID
     *
     * @mbggenerated
     */
    public BigDecimal getFkGoodsId() {
        return fkGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECORDS.FK_GOODS_ID
     *
     * @param fkGoodsId the value for TBL_RECORDS.FK_GOODS_ID
     *
     * @mbggenerated
     */
    public void setFkGoodsId(BigDecimal fkGoodsId) {
        this.fkGoodsId = fkGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECORDS.FK_SUPPL_ID
     *
     * @return the value of TBL_RECORDS.FK_SUPPL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getFkSupplId() {
        return fkSupplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECORDS.FK_SUPPL_ID
     *
     * @param fkSupplId the value for TBL_RECORDS.FK_SUPPL_ID
     *
     * @mbggenerated
     */
    public void setFkSupplId(BigDecimal fkSupplId) {
        this.fkSupplId = fkSupplId;
    }

    public String getRecoRecoder() {
        return recoRecoder;
    }

    public void setRecoRecoder(String recoRecoder) {
        this.recoRecoder = recoRecoder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECORDS.RECO_NUMBER
     *
     * @return the value of TBL_RECORDS.RECO_NUMBER
     *
     * @mbggenerated
     */

    public String getRecoNumber() {
        return recoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECORDS.RECO_NUMBER
     *
     * @param recoNumber the value for TBL_RECORDS.RECO_NUMBER
     *
     * @mbggenerated
     */
    public void setRecoNumber(String recoNumber) {
        this.recoNumber = recoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECORDS.RECO_DATE
     *
     * @return the value of TBL_RECORDS.RECO_DATE
     *
     * @mbggenerated
     */
    public String getRecoDate() {
        return recoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECORDS.RECO_DATE
     *
     * @param recoDate the value for TBL_RECORDS.RECO_DATE
     *
     * @mbggenerated
     */
    public void setRecoDate(String recoDate) {
        this.recoDate = recoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECORDS.RECO_OPERATION
     *
     * @return the value of TBL_RECORDS.RECO_OPERATION
     *
     * @mbggenerated
     */
    public String getRecoOperation() {
        return recoOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECORDS.RECO_OPERATION
     *
     * @param recoOperation the value for TBL_RECORDS.RECO_OPERATION
     *
     * @mbggenerated
     */
    public void setRecoOperation(String recoOperation) {
        this.recoOperation = recoOperation == null ? null : recoOperation.trim();
    }
}