package com.cuit.june.pojo;

import java.math.BigDecimal;

public class TblSupplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SUPPLIER.PK_ID
     *
     * @mbggenerated
     */
    private BigDecimal pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SUPPLIER.SUPP_NUMBER
     *
     * @mbggenerated
     */
    private String suppNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SUPPLIER.SUPP_NAME
     *
     * @mbggenerated
     */
    private String suppName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SUPPLIER.SUPP_PHONE
     *
     * @mbggenerated
     */
    private String suppPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SUPPLIER.SUPP_ADDR
     *
     * @mbggenerated
     */
    private String suppAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SUPPLIER.PK_ID
     *
     * @return the value of TBL_SUPPLIER.PK_ID
     *
     * @mbggenerated
     */

    public TblSupplier(BigDecimal pkId,String suppNumber,String suppName,String suppPhone,String suppAddr){
        this.pkId = pkId;
        this.suppNumber = suppNumber;
        this.suppName = suppName;
        this.suppPhone = suppPhone;
        this.suppAddr = suppAddr;
    }

    public TblSupplier(String suppNumber,String suppName,String suppPhone,String suppAddr){
        this.suppNumber = suppNumber;
        this.suppName = suppName;
        this.suppPhone = suppPhone;
        this.suppAddr = suppAddr;
    }
    public BigDecimal getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SUPPLIER.PK_ID
     *
     * @param pkId the value for TBL_SUPPLIER.PK_ID
     *
     * @mbggenerated
     */
    public void setPkId(BigDecimal pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SUPPLIER.SUPP_NUMBER
     *
     * @return the value of TBL_SUPPLIER.SUPP_NUMBER
     *
     * @mbggenerated
     */
    public String getSuppNumber() {
        return suppNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SUPPLIER.SUPP_NUMBER
     *
     * @param suppNumber the value for TBL_SUPPLIER.SUPP_NUMBER
     *
     * @mbggenerated
     */
    public void setSuppNumber(String suppNumber) {
        this.suppNumber = suppNumber == null ? null : suppNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SUPPLIER.SUPP_NAME
     *
     * @return the value of TBL_SUPPLIER.SUPP_NAME
     *
     * @mbggenerated
     */
    public String getSuppName() {
        return suppName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SUPPLIER.SUPP_NAME
     *
     * @param suppName the value for TBL_SUPPLIER.SUPP_NAME
     *
     * @mbggenerated
     */
    public void setSuppName(String suppName) {
        this.suppName = suppName == null ? null : suppName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SUPPLIER.SUPP_PHONE
     *
     * @return the value of TBL_SUPPLIER.SUPP_PHONE
     *
     * @mbggenerated
     */
    public String getSuppPhone() {
        return suppPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SUPPLIER.SUPP_PHONE
     *
     * @param suppPhone the value for TBL_SUPPLIER.SUPP_PHONE
     *
     * @mbggenerated
     */
    public void setSuppPhone(String suppPhone) {
        this.suppPhone = suppPhone == null ? null : suppPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SUPPLIER.SUPP_ADDR
     *
     * @return the value of TBL_SUPPLIER.SUPP_ADDR
     *
     * @mbggenerated
     */
    public String getSuppAddr() {
        return suppAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SUPPLIER.SUPP_ADDR
     *
     * @param suppAddr the value for TBL_SUPPLIER.SUPP_ADDR
     *
     * @mbggenerated
     */
    public void setSuppAddr(String suppAddr) {
        this.suppAddr = suppAddr == null ? null : suppAddr.trim();
    }
}